name: Auto Merge

on:
  pull_request:
    types:
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open'
    steps:
      - name: Enable auto-merge for PRs with "automerge" label
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
