name: Enable Auto Merge

on:
  pull_request_target:          # ← pull_request 가 아니라 pull_request_target
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      # ① PR 작성자의 브랜치를 정확히 체크아웃
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref:  ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0           # (선택) 전체 히스토리 필요 시

      # ② Auto-merge 플래그만 설정
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge      # 필요 시 squash‧rebase 변경 가능
